### ISSUE TITLE
GSM interception testing

### ISSUE THREAD

**Issue by wolfyy59** [sharyer/gsmevil2#17]
excuse me am newbie about radio signals , can i intercept sms messages on 3g 4glte? or it work only on 2g? because when i make a call 
when i see the frequency its 900mhz same as receiving smss so i thought that i can intercept my phone messages outside on 4g lte and 3g because its delivered only on 900mhz thanks

**Comment by Gourav9111** [comment]
Can you please share commonds that you use to capture Sms .

**Comment by ninjhacks** [comment]
yes, you can if no encryption is used.
