### ISSUE TITLE
Discord Server invite broken/down ?

### ISSUE THREAD

**Issue by spookycheekybreeky** [sharyer/gsmevil2#19]
Hi, i been trying to join the ninjhacks discord with the custom invite but its seam that the invite link is down / custom invite is not set.

Can you provide a new invite ? Thank

![image](https://github.com/ninjhacks/gsmevil2/assets/74380213/dea766e5-fa62-4af1-87a4-cdf760c0668f)

**Comment by ninjhacks** [comment]
Now working again
