### ISSUE TITLE
Timing advance and IMSI

### ISSUE THREAD

**Issue by Juananab** [sharyer/gsmevil2#21]

**Comment by ninjhacks** [comment]
Not sure exactly what you trying to say because I lost context it's been very long since I used last time.

**Comment by Juananab** [comment]
The "timing advance" is a parameter included in the immediate response packets. My specific interest lies in establishing a correlation between this "timing advance" value and an IMSI in order to estimate the approximate distance between a user and a BTS, but I'm not realy sure if this is possible.
